
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RVALOR = 33;
  public static final int PAR_DER = 4;
  public static final int DOSPUNTOS = 13;
  public static final int DISTINTO = 58;
  public static final int COMPARADOR = 57;
  public static final int RSTRING = 39;
  public static final int RTRUE = 42;
  public static final int RWHILE = 51;
  public static final int POR = 19;
  public static final int RDOWHILE = 52;
  public static final int ENTERO = 21;
  public static final int RVOID = 26;
  public static final int RDEFGLOBAL = 28;
  public static final int COR_DER = 6;
  public static final int RFALSE = 43;
  public static final int RGRAFIPIE = 30;
  public static final int RELSE = 45;
  public static final int NOT = 61;
  public static final int AND = 59;
  public static final int IGUAL = 15;
  public static final int OR = 60;
  public static final int RDOUBLE = 37;
  public static final int DIV = 20;
  public static final int UMENOS = 25;
  public static final int RCONSOLA = 53;
  public static final int LLAV_IZQ = 7;
  public static final int ID = 23;
  public static final int EOF = 0;
  public static final int DECIMAL = 22;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 24;
  public static final int MENOS = 18;
  public static final int RWRITE = 54;
  public static final int MAYOR_QUE = 9;
  public static final int RTITULO = 31;
  public static final int PAR_IZQ = 3;
  public static final int RCHAR = 38;
  public static final int RTITULOY = 35;
  public static final int RTITULOX = 34;
  public static final int RCASE = 48;
  public static final int PUNTO = 12;
  public static final int VACIO = 16;
  public static final int DOLLAR = 14;
  public static final int MAYOR_IGUAL = 55;
  public static final int RNEWVALOR = 44;
  public static final int COR_IZQ = 5;
  public static final int RDEFAU = 49;
  public static final int PTCOMA = 2;
  public static final int RSWITCH = 46;
  public static final int RINT = 36;
  public static final int LLAV_DER = 8;
  public static final int REJEX = 32;
  public static final int MENOR_QUE = 10;
  public static final int MENOR_IGUAL = 56;
  public static final int RFOR = 50;
  public static final int RBOOL = 40;
  public static final int RGRAFIBARRAS = 29;
  public static final int RBREAK = 47;
  public static final int RIF = 41;
  public static final int MAS = 17;
  public static final int RMAIN = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "MAYOR_QUE",
  "MENOR_QUE",
  "COMA",
  "PUNTO",
  "DOSPUNTOS",
  "DOLLAR",
  "IGUAL",
  "VACIO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CADENA",
  "UMENOS",
  "RVOID",
  "RMAIN",
  "RDEFGLOBAL",
  "RGRAFIBARRAS",
  "RGRAFIPIE",
  "RTITULO",
  "REJEX",
  "RVALOR",
  "RTITULOX",
  "RTITULOY",
  "RINT",
  "RDOUBLE",
  "RCHAR",
  "RSTRING",
  "RBOOL",
  "RIF",
  "RTRUE",
  "RFALSE",
  "RNEWVALOR",
  "RELSE",
  "RSWITCH",
  "RBREAK",
  "RCASE",
  "RDEFAU",
  "RFOR",
  "RWHILE",
  "RDOWHILE",
  "RCONSOLA",
  "RWRITE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "COMPARADOR",
  "DISTINTO",
  "AND",
  "OR",
  "NOT"
  };
}

