
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 13;
  public static final int LETRA = 11;
  public static final int DECIMAL = 10;
  public static final int LLA_IZQ = 2;
  public static final int MAYOR_QUE = 5;
  public static final int LLA_DER = 3;
  public static final int ENTER = 16;
  public static final int ID = 12;
  public static final int SPACE = 15;
  public static final int CADENA1 = 14;
  public static final int DOS_PUNTOS = 7;
  public static final int CARACTER = 17;
  public static final int COMA = 8;
  public static final int MENOR_QUE = 4;
  public static final int COMILLA_DOBLE = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ENTERO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLA_IZQ",
  "LLA_DER",
  "MENOR_QUE",
  "MAYOR_QUE",
  "COMILLA_DOBLE",
  "DOS_PUNTOS",
  "COMA",
  "ENTERO",
  "DECIMAL",
  "LETRA",
  "ID",
  "CADENA",
  "CADENA1",
  "SPACE",
  "ENTER",
  "CARACTER"
  };
}

